package io.github.qianlixunbai.workspace.common;

public enum ErrorCode {
    PROVIDER_UNAVAILABLE, MODEL_UNAVAILABLE, TASK_CANCELLED, TASK_TIMEOUT,
    QUEUE_FULL, INVALID_REQUEST, POLICY_DENIED, PROVIDER_RESPONSE_INVALID,
    INTERNAL_ERROR, UNAUTHORIZED, TASK_NOT_FOUND
}
