package io.github.qianlixunbai.workspace.common;

public enum ErrorCode {
    WEB_DISABLED, WEB_TARGET_INVALID, WEB_TARGET_NOT_PUBLIC, WEB_DNS_FAILED, WEB_TLS_FAILED,
    WEB_TIMEOUT, WEB_REDIRECT_DENIED, WEB_RESPONSE_TOO_LARGE, WEB_CONTENT_TYPE_UNSUPPORTED,
    WEB_CONTENT_INVALID, WEB_FETCH_FAILED, WEB_FETCH_NOT_FOUND,
    PROVIDER_UNAVAILABLE, MODEL_UNAVAILABLE, TASK_CANCELLED, TASK_TIMEOUT,
    QUEUE_FULL, INVALID_REQUEST, POLICY_DENIED, PROVIDER_RESPONSE_INVALID,
    INTERNAL_ERROR, UNAUTHORIZED, TASK_NOT_FOUND,
    MEMORY_NOT_FOUND, MEMORY_REVISION_CONFLICT, MEMORY_LIMIT_EXCEEDED,
    MEMORY_INVALID, MEMORY_STORAGE_UNAVAILABLE, MEMORY_SCHEMA_UNSUPPORTED, MEMORY_SELECTION_STALE,
    MEMORY_BACKUP_INVALID, MEMORY_BACKUP_UNSUPPORTED, MEMORY_BACKUP_TOO_LARGE,
    MEMORY_RESTORE_TARGET_NOT_EMPTY, MEMORY_EXPORT_FAILED, MEMORY_RESTORE_FAILED,
    WORKSPACE_BACKUP_INVALID, WORKSPACE_BACKUP_UNSUPPORTED, WORKSPACE_BACKUP_TOO_LARGE,
    WORKSPACE_BACKUP_CONFLICT, WORKSPACE_EXPORT_FAILED, WORKSPACE_RESTORE_FAILED, WORKSPACE_RESTORE_TARGET_NOT_EMPTY,
    CONVERSATION_NOT_FOUND, CONVERSATION_INVALID, CONVERSATION_CONFLICT,
    CONVERSATION_LIMIT_EXCEEDED, CONVERSATION_STORAGE_UNAVAILABLE,
    KNOWLEDGE_INVALID_SOURCE, KNOWLEDGE_UNSUPPORTED_TYPE, KNOWLEDGE_INVALID_UTF8, KNOWLEDGE_SOURCE_TOO_LARGE,
    KNOWLEDGE_LIMIT_EXCEEDED, KNOWLEDGE_DUPLICATE_SOURCE, KNOWLEDGE_REVISION_CONFLICT, KNOWLEDGE_NOT_FOUND,
    KNOWLEDGE_QUEUE_FULL, KNOWLEDGE_INGESTION_FAILED, KNOWLEDGE_INTERRUPTED, KNOWLEDGE_CANCELLED,
    KNOWLEDGE_STORAGE_UNAVAILABLE, KNOWLEDGE_SCHEMA_UNSUPPORTED, KNOWLEDGE_DELETE_INCOMPLETE,
    KNOWLEDGE_BACKUP_INVALID, KNOWLEDGE_BACKUP_UNSUPPORTED, KNOWLEDGE_BACKUP_TOO_LARGE,
    KNOWLEDGE_BACKUP_CONFLICT, KNOWLEDGE_RESTORE_TARGET_NOT_EMPTY, KNOWLEDGE_RESTORE_FAILED, KNOWLEDGE_EXPORT_FAILED,
    KNOWLEDGE_SEARCH_INVALID, KNOWLEDGE_QUERY_TOO_COMPLEX, KNOWLEDGE_INDEX_NOT_READY,
    KNOWLEDGE_INDEX_UNAVAILABLE, KNOWLEDGE_INDEX_LIMIT_EXCEEDED, KNOWLEDGE_INDEX_REBUILD_FAILED
}
