package io.github.qianlixunbai.workspace.common;

public enum ErrorCode {
    PROVIDER_UNAVAILABLE, MODEL_UNAVAILABLE, TASK_CANCELLED, TASK_TIMEOUT,
    QUEUE_FULL, INVALID_REQUEST, POLICY_DENIED, PROVIDER_RESPONSE_INVALID,
    INTERNAL_ERROR, UNAUTHORIZED, TASK_NOT_FOUND,
    MEMORY_NOT_FOUND, MEMORY_REVISION_CONFLICT, MEMORY_LIMIT_EXCEEDED,
    MEMORY_INVALID, MEMORY_STORAGE_UNAVAILABLE, MEMORY_SCHEMA_UNSUPPORTED, MEMORY_SELECTION_STALE,
    MEMORY_BACKUP_INVALID, MEMORY_BACKUP_UNSUPPORTED, MEMORY_BACKUP_TOO_LARGE,
    MEMORY_RESTORE_TARGET_NOT_EMPTY, MEMORY_EXPORT_FAILED, MEMORY_RESTORE_FAILED
}
