package io.github.qianlixunbai.workspace.provider.ollama;

import tools.jackson.databind.json.JsonMapper;
import java.util.*;

/** Deterministic v0.40.0 local single-GGUF shape; provenance is documented in the MMF-1 candidate report. */
public final class OllamaFixtures {
    private static final JsonMapper JSON = JsonMapper.builder().build();
    private static final Map<String, Object> DETAILS = Map.of("parent_model", "", "format", "gguf", "family", "qwen35",
            "families", List.of("qwen35"), "parameter_size", "4B", "quantization_level", "Q4_K_M", "runner", "ggml");
    public static String tags(String model, String digest) {
        var details = new HashMap<>(DETAILS); details.put("context_length", 32768); details.put("embedding_length", 2560);
        return JSON.writeValueAsString(Map.of("models", List.of(Map.of("name", model, "model", model, "digest", digest,
                "modified_at", "2026-10-08T00:00:00Z", "size", 2500000000L, "details", details))));
    }
    public static String show() {
        return JSON.writeValueAsString(Map.of("details", DETAILS, "capabilities", List.of("completion", "thinking"),
                "model_info", Map.of("general.architecture", "qwen35", "qwen35.context_length", 32768),
                "modelfile", "# Modelfile generated by \"ollama show\"\nFROM /isolated/models/blobs/sha256-" + "b".repeat(64) + "\nTEMPLATE \"{{ .Prompt }}\"\n"));
    }
    public static String completed(String model, String output) {
        return JSON.writeValueAsString(Map.of("model", model, "created_at", "2026-10-08T00:00:00Z", "done", true,
                "done_reason", "stop", "message", Map.of("role", "assistant", "content", output)));
    }
}
